// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weixin.proto

package com.excheer.protobuf;

public final class WeiXin {
  private WeiXin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 errcode = 1;
    boolean hasErrcode();
    int getErrcode();
    
    // optional string errmsg = 2;
    boolean hasErrmsg();
    String getErrmsg();
  }
  public static final class BaseResponse extends
      com.google.protobuf.GeneratedMessage
      implements BaseResponseOrBuilder {
    // Use BaseResponse.newBuilder() to construct.
    private BaseResponse(Builder builder) {
      super(builder);
    }
    private BaseResponse(boolean noInit) {}
    
    private static final BaseResponse defaultInstance;
    public static BaseResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BaseResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_BaseResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_BaseResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 errcode = 1;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errcode_;
    public boolean hasErrcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getErrcode() {
      return errcode_;
    }
    
    // optional string errmsg = 2;
    public static final int ERRMSG_FIELD_NUMBER = 2;
    private java.lang.Object errmsg_;
    public boolean hasErrmsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getErrmsg() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errmsg_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrmsgBytes() {
      java.lang.Object ref = errmsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      errcode_ = 0;
      errmsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrmsgBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrmsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.excheer.protobuf.WeiXin.BaseResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.excheer.protobuf.WeiXin.BaseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_BaseResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_BaseResponse_fieldAccessorTable;
      }
      
      // Construct using com.excheer.protobuf.WeiXin.BaseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errmsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.excheer.protobuf.WeiXin.BaseResponse.getDescriptor();
      }
      
      public com.excheer.protobuf.WeiXin.BaseResponse getDefaultInstanceForType() {
        return com.excheer.protobuf.WeiXin.BaseResponse.getDefaultInstance();
      }
      
      public com.excheer.protobuf.WeiXin.BaseResponse build() {
        com.excheer.protobuf.WeiXin.BaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.excheer.protobuf.WeiXin.BaseResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.excheer.protobuf.WeiXin.BaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.excheer.protobuf.WeiXin.BaseResponse buildPartial() {
        com.excheer.protobuf.WeiXin.BaseResponse result = new com.excheer.protobuf.WeiXin.BaseResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errcode_ = errcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errmsg_ = errmsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.excheer.protobuf.WeiXin.BaseResponse) {
          return mergeFrom((com.excheer.protobuf.WeiXin.BaseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.excheer.protobuf.WeiXin.BaseResponse other) {
        if (other == com.excheer.protobuf.WeiXin.BaseResponse.getDefaultInstance()) return this;
        if (other.hasErrcode()) {
          setErrcode(other.getErrcode());
        }
        if (other.hasErrmsg()) {
          setErrmsg(other.getErrmsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errcode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errmsg_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 errcode = 1;
      private int errcode_ ;
      public boolean hasErrcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getErrcode() {
        return errcode_;
      }
      public Builder setErrcode(int value) {
        bitField0_ |= 0x00000001;
        errcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errcode_ = 0;
        onChanged();
        return this;
      }
      
      // optional string errmsg = 2;
      private java.lang.Object errmsg_ = "";
      public boolean hasErrmsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getErrmsg() {
        java.lang.Object ref = errmsg_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errmsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrmsg(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errmsg_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrmsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errmsg_ = getDefaultInstance().getErrmsg();
        onChanged();
        return this;
      }
      void setErrmsg(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        errmsg_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:mmbp_open.BaseResponse)
    }
    
    static {
      defaultInstance = new BaseResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mmbp_open.BaseResponse)
  }
  
  public interface WristbandRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .mmbp_open.WristbandRequest.StepDataItem StepData = 1;
    java.util.List<com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem> 
        getStepDataList();
    com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem getStepData(int index);
    int getStepDataCount();
    java.util.List<? extends com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder> 
        getStepDataOrBuilderList();
    com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder getStepDataOrBuilder(
        int index);
    
    // optional bytes ExtData = 2;
    boolean hasExtData();
    com.google.protobuf.ByteString getExtData();
  }
  public static final class WristbandRequest extends
      com.google.protobuf.GeneratedMessage
      implements WristbandRequestOrBuilder {
    // Use WristbandRequest.newBuilder() to construct.
    private WristbandRequest(Builder builder) {
      super(builder);
    }
    private WristbandRequest(boolean noInit) {}
    
    private static final WristbandRequest defaultInstance;
    public static WristbandRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public WristbandRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_fieldAccessorTable;
    }
    
    public interface StepDataItemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional uint32 Step = 1;
      boolean hasStep();
      int getStep();
      
      // optional uint32 Timestamp = 2;
      boolean hasTimestamp();
      int getTimestamp();
    }
    public static final class StepDataItem extends
        com.google.protobuf.GeneratedMessage
        implements StepDataItemOrBuilder {
      // Use StepDataItem.newBuilder() to construct.
      private StepDataItem(Builder builder) {
        super(builder);
      }
      private StepDataItem(boolean noInit) {}
      
      private static final StepDataItem defaultInstance;
      public static StepDataItem getDefaultInstance() {
        return defaultInstance;
      }
      
      public StepDataItem getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_StepDataItem_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_StepDataItem_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional uint32 Step = 1;
      public static final int STEP_FIELD_NUMBER = 1;
      private int step_;
      public boolean hasStep() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getStep() {
        return step_;
      }
      
      // optional uint32 Timestamp = 2;
      public static final int TIMESTAMP_FIELD_NUMBER = 2;
      private int timestamp_;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTimestamp() {
        return timestamp_;
      }
      
      private void initFields() {
        step_ = 0;
        timestamp_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeUInt32(1, step_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeUInt32(2, timestamp_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, step_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, timestamp_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_StepDataItem_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_StepDataItem_fieldAccessorTable;
        }
        
        // Construct using com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          step_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          timestamp_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.getDescriptor();
        }
        
        public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem getDefaultInstanceForType() {
          return com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.getDefaultInstance();
        }
        
        public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem build() {
          com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem buildPartial() {
          com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem result = new com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.step_ = step_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.timestamp_ = timestamp_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem) {
            return mergeFrom((com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem other) {
          if (other == com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.getDefaultInstance()) return this;
          if (other.hasStep()) {
            setStep(other.getStep());
          }
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                step_ = input.readUInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                timestamp_ = input.readUInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional uint32 Step = 1;
        private int step_ ;
        public boolean hasStep() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getStep() {
          return step_;
        }
        public Builder setStep(int value) {
          bitField0_ |= 0x00000001;
          step_ = value;
          onChanged();
          return this;
        }
        public Builder clearStep() {
          bitField0_ = (bitField0_ & ~0x00000001);
          step_ = 0;
          onChanged();
          return this;
        }
        
        // optional uint32 Timestamp = 2;
        private int timestamp_ ;
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getTimestamp() {
          return timestamp_;
        }
        public Builder setTimestamp(int value) {
          bitField0_ |= 0x00000002;
          timestamp_ = value;
          onChanged();
          return this;
        }
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000002);
          timestamp_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:mmbp_open.WristbandRequest.StepDataItem)
      }
      
      static {
        defaultInstance = new StepDataItem(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:mmbp_open.WristbandRequest.StepDataItem)
    }
    
    private int bitField0_;
    // repeated .mmbp_open.WristbandRequest.StepDataItem StepData = 1;
    public static final int STEPDATA_FIELD_NUMBER = 1;
    private java.util.List<com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem> stepData_;
    public java.util.List<com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem> getStepDataList() {
      return stepData_;
    }
    public java.util.List<? extends com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder> 
        getStepDataOrBuilderList() {
      return stepData_;
    }
    public int getStepDataCount() {
      return stepData_.size();
    }
    public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem getStepData(int index) {
      return stepData_.get(index);
    }
    public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder getStepDataOrBuilder(
        int index) {
      return stepData_.get(index);
    }
    
    // optional bytes ExtData = 2;
    public static final int EXTDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString extData_;
    public boolean hasExtData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getExtData() {
      return extData_;
    }
    
    private void initFields() {
      stepData_ = java.util.Collections.emptyList();
      extData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < stepData_.size(); i++) {
        output.writeMessage(1, stepData_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, extData_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < stepData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stepData_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, extData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristbandRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.excheer.protobuf.WeiXin.WristbandRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.excheer.protobuf.WeiXin.WristbandRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristbandRequest_fieldAccessorTable;
      }
      
      // Construct using com.excheer.protobuf.WeiXin.WristbandRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStepDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (stepDataBuilder_ == null) {
          stepData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          stepDataBuilder_.clear();
        }
        extData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.excheer.protobuf.WeiXin.WristbandRequest.getDescriptor();
      }
      
      public com.excheer.protobuf.WeiXin.WristbandRequest getDefaultInstanceForType() {
        return com.excheer.protobuf.WeiXin.WristbandRequest.getDefaultInstance();
      }
      
      public com.excheer.protobuf.WeiXin.WristbandRequest build() {
        com.excheer.protobuf.WeiXin.WristbandRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.excheer.protobuf.WeiXin.WristbandRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.excheer.protobuf.WeiXin.WristbandRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.excheer.protobuf.WeiXin.WristbandRequest buildPartial() {
        com.excheer.protobuf.WeiXin.WristbandRequest result = new com.excheer.protobuf.WeiXin.WristbandRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (stepDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            stepData_ = java.util.Collections.unmodifiableList(stepData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stepData_ = stepData_;
        } else {
          result.stepData_ = stepDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.extData_ = extData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.excheer.protobuf.WeiXin.WristbandRequest) {
          return mergeFrom((com.excheer.protobuf.WeiXin.WristbandRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.excheer.protobuf.WeiXin.WristbandRequest other) {
        if (other == com.excheer.protobuf.WeiXin.WristbandRequest.getDefaultInstance()) return this;
        if (stepDataBuilder_ == null) {
          if (!other.stepData_.isEmpty()) {
            if (stepData_.isEmpty()) {
              stepData_ = other.stepData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStepDataIsMutable();
              stepData_.addAll(other.stepData_);
            }
            onChanged();
          }
        } else {
          if (!other.stepData_.isEmpty()) {
            if (stepDataBuilder_.isEmpty()) {
              stepDataBuilder_.dispose();
              stepDataBuilder_ = null;
              stepData_ = other.stepData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stepDataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStepDataFieldBuilder() : null;
            } else {
              stepDataBuilder_.addAllMessages(other.stepData_);
            }
          }
        }
        if (other.hasExtData()) {
          setExtData(other.getExtData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder subBuilder = com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addStepData(subBuilder.buildPartial());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              extData_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .mmbp_open.WristbandRequest.StepDataItem StepData = 1;
      private java.util.List<com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem> stepData_ =
        java.util.Collections.emptyList();
      private void ensureStepDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          stepData_ = new java.util.ArrayList<com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem>(stepData_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder> stepDataBuilder_;
      
      public java.util.List<com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem> getStepDataList() {
        if (stepDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stepData_);
        } else {
          return stepDataBuilder_.getMessageList();
        }
      }
      public int getStepDataCount() {
        if (stepDataBuilder_ == null) {
          return stepData_.size();
        } else {
          return stepDataBuilder_.getCount();
        }
      }
      public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem getStepData(int index) {
        if (stepDataBuilder_ == null) {
          return stepData_.get(index);
        } else {
          return stepDataBuilder_.getMessage(index);
        }
      }
      public Builder setStepData(
          int index, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem value) {
        if (stepDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepDataIsMutable();
          stepData_.set(index, value);
          onChanged();
        } else {
          stepDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setStepData(
          int index, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder builderForValue) {
        if (stepDataBuilder_ == null) {
          ensureStepDataIsMutable();
          stepData_.set(index, builderForValue.build());
          onChanged();
        } else {
          stepDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addStepData(com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem value) {
        if (stepDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepDataIsMutable();
          stepData_.add(value);
          onChanged();
        } else {
          stepDataBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addStepData(
          int index, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem value) {
        if (stepDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepDataIsMutable();
          stepData_.add(index, value);
          onChanged();
        } else {
          stepDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addStepData(
          com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder builderForValue) {
        if (stepDataBuilder_ == null) {
          ensureStepDataIsMutable();
          stepData_.add(builderForValue.build());
          onChanged();
        } else {
          stepDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addStepData(
          int index, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder builderForValue) {
        if (stepDataBuilder_ == null) {
          ensureStepDataIsMutable();
          stepData_.add(index, builderForValue.build());
          onChanged();
        } else {
          stepDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllStepData(
          java.lang.Iterable<? extends com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem> values) {
        if (stepDataBuilder_ == null) {
          ensureStepDataIsMutable();
          super.addAll(values, stepData_);
          onChanged();
        } else {
          stepDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearStepData() {
        if (stepDataBuilder_ == null) {
          stepData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stepDataBuilder_.clear();
        }
        return this;
      }
      public Builder removeStepData(int index) {
        if (stepDataBuilder_ == null) {
          ensureStepDataIsMutable();
          stepData_.remove(index);
          onChanged();
        } else {
          stepDataBuilder_.remove(index);
        }
        return this;
      }
      public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder getStepDataBuilder(
          int index) {
        return getStepDataFieldBuilder().getBuilder(index);
      }
      public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder getStepDataOrBuilder(
          int index) {
        if (stepDataBuilder_ == null) {
          return stepData_.get(index);  } else {
          return stepDataBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder> 
           getStepDataOrBuilderList() {
        if (stepDataBuilder_ != null) {
          return stepDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stepData_);
        }
      }
      public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder addStepDataBuilder() {
        return getStepDataFieldBuilder().addBuilder(
            com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.getDefaultInstance());
      }
      public com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder addStepDataBuilder(
          int index) {
        return getStepDataFieldBuilder().addBuilder(
            index, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.getDefaultInstance());
      }
      public java.util.List<com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder> 
           getStepDataBuilderList() {
        return getStepDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder> 
          getStepDataFieldBuilder() {
        if (stepDataBuilder_ == null) {
          stepDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder, com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItemOrBuilder>(
                  stepData_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          stepData_ = null;
        }
        return stepDataBuilder_;
      }
      
      // optional bytes ExtData = 2;
      private com.google.protobuf.ByteString extData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasExtData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getExtData() {
        return extData_;
      }
      public Builder setExtData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        extData_ = value;
        onChanged();
        return this;
      }
      public Builder clearExtData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        extData_ = getDefaultInstance().getExtData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:mmbp_open.WristbandRequest)
    }
    
    static {
      defaultInstance = new WristbandRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mmbp_open.WristbandRequest)
  }
  
  public interface WristBandResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .mmbp_open.BaseResponse BaseResp = 1;
    boolean hasBaseResp();
    com.excheer.protobuf.WeiXin.BaseResponse getBaseResp();
    com.excheer.protobuf.WeiXin.BaseResponseOrBuilder getBaseRespOrBuilder();
  }
  public static final class WristBandResponse extends
      com.google.protobuf.GeneratedMessage
      implements WristBandResponseOrBuilder {
    // Use WristBandResponse.newBuilder() to construct.
    private WristBandResponse(Builder builder) {
      super(builder);
    }
    private WristBandResponse(boolean noInit) {}
    
    private static final WristBandResponse defaultInstance;
    public static WristBandResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public WristBandResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .mmbp_open.BaseResponse BaseResp = 1;
    public static final int BASERESP_FIELD_NUMBER = 1;
    private com.excheer.protobuf.WeiXin.BaseResponse baseResp_;
    public boolean hasBaseResp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.excheer.protobuf.WeiXin.BaseResponse getBaseResp() {
      return baseResp_;
    }
    public com.excheer.protobuf.WeiXin.BaseResponseOrBuilder getBaseRespOrBuilder() {
      return baseResp_;
    }
    
    private void initFields() {
      baseResp_ = com.excheer.protobuf.WeiXin.BaseResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, baseResp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, baseResp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.excheer.protobuf.WeiXin.WristBandResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.excheer.protobuf.WeiXin.WristBandResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandResponse_fieldAccessorTable;
      }
      
      // Construct using com.excheer.protobuf.WeiXin.WristBandResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBaseRespFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (baseRespBuilder_ == null) {
          baseResp_ = com.excheer.protobuf.WeiXin.BaseResponse.getDefaultInstance();
        } else {
          baseRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.excheer.protobuf.WeiXin.WristBandResponse.getDescriptor();
      }
      
      public com.excheer.protobuf.WeiXin.WristBandResponse getDefaultInstanceForType() {
        return com.excheer.protobuf.WeiXin.WristBandResponse.getDefaultInstance();
      }
      
      public com.excheer.protobuf.WeiXin.WristBandResponse build() {
        com.excheer.protobuf.WeiXin.WristBandResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.excheer.protobuf.WeiXin.WristBandResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.excheer.protobuf.WeiXin.WristBandResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.excheer.protobuf.WeiXin.WristBandResponse buildPartial() {
        com.excheer.protobuf.WeiXin.WristBandResponse result = new com.excheer.protobuf.WeiXin.WristBandResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (baseRespBuilder_ == null) {
          result.baseResp_ = baseResp_;
        } else {
          result.baseResp_ = baseRespBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.excheer.protobuf.WeiXin.WristBandResponse) {
          return mergeFrom((com.excheer.protobuf.WeiXin.WristBandResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.excheer.protobuf.WeiXin.WristBandResponse other) {
        if (other == com.excheer.protobuf.WeiXin.WristBandResponse.getDefaultInstance()) return this;
        if (other.hasBaseResp()) {
          mergeBaseResp(other.getBaseResp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.excheer.protobuf.WeiXin.BaseResponse.Builder subBuilder = com.excheer.protobuf.WeiXin.BaseResponse.newBuilder();
              if (hasBaseResp()) {
                subBuilder.mergeFrom(getBaseResp());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBaseResp(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .mmbp_open.BaseResponse BaseResp = 1;
      private com.excheer.protobuf.WeiXin.BaseResponse baseResp_ = com.excheer.protobuf.WeiXin.BaseResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.excheer.protobuf.WeiXin.BaseResponse, com.excheer.protobuf.WeiXin.BaseResponse.Builder, com.excheer.protobuf.WeiXin.BaseResponseOrBuilder> baseRespBuilder_;
      public boolean hasBaseResp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.excheer.protobuf.WeiXin.BaseResponse getBaseResp() {
        if (baseRespBuilder_ == null) {
          return baseResp_;
        } else {
          return baseRespBuilder_.getMessage();
        }
      }
      public Builder setBaseResp(com.excheer.protobuf.WeiXin.BaseResponse value) {
        if (baseRespBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseResp_ = value;
          onChanged();
        } else {
          baseRespBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setBaseResp(
          com.excheer.protobuf.WeiXin.BaseResponse.Builder builderForValue) {
        if (baseRespBuilder_ == null) {
          baseResp_ = builderForValue.build();
          onChanged();
        } else {
          baseRespBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeBaseResp(com.excheer.protobuf.WeiXin.BaseResponse value) {
        if (baseRespBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              baseResp_ != com.excheer.protobuf.WeiXin.BaseResponse.getDefaultInstance()) {
            baseResp_ =
              com.excheer.protobuf.WeiXin.BaseResponse.newBuilder(baseResp_).mergeFrom(value).buildPartial();
          } else {
            baseResp_ = value;
          }
          onChanged();
        } else {
          baseRespBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearBaseResp() {
        if (baseRespBuilder_ == null) {
          baseResp_ = com.excheer.protobuf.WeiXin.BaseResponse.getDefaultInstance();
          onChanged();
        } else {
          baseRespBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.excheer.protobuf.WeiXin.BaseResponse.Builder getBaseRespBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseRespFieldBuilder().getBuilder();
      }
      public com.excheer.protobuf.WeiXin.BaseResponseOrBuilder getBaseRespOrBuilder() {
        if (baseRespBuilder_ != null) {
          return baseRespBuilder_.getMessageOrBuilder();
        } else {
          return baseResp_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.excheer.protobuf.WeiXin.BaseResponse, com.excheer.protobuf.WeiXin.BaseResponse.Builder, com.excheer.protobuf.WeiXin.BaseResponseOrBuilder> 
          getBaseRespFieldBuilder() {
        if (baseRespBuilder_ == null) {
          baseRespBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.excheer.protobuf.WeiXin.BaseResponse, com.excheer.protobuf.WeiXin.BaseResponse.Builder, com.excheer.protobuf.WeiXin.BaseResponseOrBuilder>(
                  baseResp_,
                  getParentForChildren(),
                  isClean());
          baseResp_ = null;
        }
        return baseRespBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:mmbp_open.WristBandResponse)
    }
    
    static {
      defaultInstance = new WristBandResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mmbp_open.WristBandResponse)
  }
  
  public interface WristBandPushOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  public static final class WristBandPush extends
      com.google.protobuf.GeneratedMessage
      implements WristBandPushOrBuilder {
    // Use WristBandPush.newBuilder() to construct.
    private WristBandPush(Builder builder) {
      super(builder);
    }
    private WristBandPush(boolean noInit) {}
    
    private static final WristBandPush defaultInstance;
    public static WristBandPush getDefaultInstance() {
      return defaultInstance;
    }
    
    public WristBandPush getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandPush_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandPush_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.excheer.protobuf.WeiXin.WristBandPush parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.excheer.protobuf.WeiXin.WristBandPush prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.excheer.protobuf.WeiXin.WristBandPushOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandPush_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.excheer.protobuf.WeiXin.internal_static_mmbp_open_WristBandPush_fieldAccessorTable;
      }
      
      // Construct using com.excheer.protobuf.WeiXin.WristBandPush.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.excheer.protobuf.WeiXin.WristBandPush.getDescriptor();
      }
      
      public com.excheer.protobuf.WeiXin.WristBandPush getDefaultInstanceForType() {
        return com.excheer.protobuf.WeiXin.WristBandPush.getDefaultInstance();
      }
      
      public com.excheer.protobuf.WeiXin.WristBandPush build() {
        com.excheer.protobuf.WeiXin.WristBandPush result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.excheer.protobuf.WeiXin.WristBandPush buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.excheer.protobuf.WeiXin.WristBandPush result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.excheer.protobuf.WeiXin.WristBandPush buildPartial() {
        com.excheer.protobuf.WeiXin.WristBandPush result = new com.excheer.protobuf.WeiXin.WristBandPush(this);
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.excheer.protobuf.WeiXin.WristBandPush) {
          return mergeFrom((com.excheer.protobuf.WeiXin.WristBandPush)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.excheer.protobuf.WeiXin.WristBandPush other) {
        if (other == com.excheer.protobuf.WeiXin.WristBandPush.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:mmbp_open.WristBandPush)
    }
    
    static {
      defaultInstance = new WristBandPush(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mmbp_open.WristBandPush)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mmbp_open_BaseResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mmbp_open_BaseResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mmbp_open_WristbandRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mmbp_open_WristbandRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mmbp_open_WristbandRequest_StepDataItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mmbp_open_WristbandRequest_StepDataItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mmbp_open_WristBandResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mmbp_open_WristBandResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mmbp_open_WristBandPush_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mmbp_open_WristBandPush_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014weixin.proto\022\tmmbp_open\"/\n\014BaseRespons" +
      "e\022\017\n\007errcode\030\001 \001(\005\022\016\n\006errmsg\030\002 \001(\t\"\220\001\n\020W" +
      "ristbandRequest\022:\n\010StepData\030\001 \003(\0132(.mmbp" +
      "_open.WristbandRequest.StepDataItem\022\017\n\007E" +
      "xtData\030\002 \001(\014\032/\n\014StepDataItem\022\014\n\004Step\030\001 \001" +
      "(\r\022\021\n\tTimestamp\030\002 \001(\r\">\n\021WristBandRespon" +
      "se\022)\n\010BaseResp\030\001 \001(\0132\027.mmbp_open.BaseRes" +
      "ponse\"\017\n\rWristBandPushB\036\n\024com.excheer.pr" +
      "otobufB\006WeiXin"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mmbp_open_BaseResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mmbp_open_BaseResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mmbp_open_BaseResponse_descriptor,
              new java.lang.String[] { "Errcode", "Errmsg", },
              com.excheer.protobuf.WeiXin.BaseResponse.class,
              com.excheer.protobuf.WeiXin.BaseResponse.Builder.class);
          internal_static_mmbp_open_WristbandRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mmbp_open_WristbandRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mmbp_open_WristbandRequest_descriptor,
              new java.lang.String[] { "StepData", "ExtData", },
              com.excheer.protobuf.WeiXin.WristbandRequest.class,
              com.excheer.protobuf.WeiXin.WristbandRequest.Builder.class);
          internal_static_mmbp_open_WristbandRequest_StepDataItem_descriptor =
            internal_static_mmbp_open_WristbandRequest_descriptor.getNestedTypes().get(0);
          internal_static_mmbp_open_WristbandRequest_StepDataItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mmbp_open_WristbandRequest_StepDataItem_descriptor,
              new java.lang.String[] { "Step", "Timestamp", },
              com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.class,
              com.excheer.protobuf.WeiXin.WristbandRequest.StepDataItem.Builder.class);
          internal_static_mmbp_open_WristBandResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_mmbp_open_WristBandResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mmbp_open_WristBandResponse_descriptor,
              new java.lang.String[] { "BaseResp", },
              com.excheer.protobuf.WeiXin.WristBandResponse.class,
              com.excheer.protobuf.WeiXin.WristBandResponse.Builder.class);
          internal_static_mmbp_open_WristBandPush_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_mmbp_open_WristBandPush_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mmbp_open_WristBandPush_descriptor,
              new java.lang.String[] { },
              com.excheer.protobuf.WeiXin.WristBandPush.class,
              com.excheer.protobuf.WeiXin.WristBandPush.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
